import { createClient } from '@supabase/supabase-js';

// ── Supabase ───────────────────────────────────────────────────────────────
const SUPABASE_URL = "https://fowlmllbyjkbedhisceo.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvd2xtbGxieWprYmVkaGlzY2VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MTkzNjQsImV4cCI6MjA4OTQ5NTM2NH0.uNBcVHHfKg7C56iQhxfu9SJ1V1XCACsuiYvy6JfR6jw"; // Anon Public Key einsetzen!
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// ── Translations ───────────────────────────────────────────────────────────
const T = {
  de: {
    flag: "🇩🇪",
    name: "Deutsch",
    anmelden: "Anmelden →",
    profil: "Profil",
    dashboard: "Dashboard",
    abmelden: "Abmelden",
    plzOrt: "PLZ oder Ort",
    alle: "Alle",
    stellenGefunden: (n) => `${n} Stellen gefunden`,
    keineStellen: "Keine Stellen gefunden",
    filterAendern: "Ändere den Filter oder PLZ",
    zurueck: "← Zurück",
    home: "Home",
    aufrufe: (n) => `${n} Aufrufe`,
    treffpunkt: "TREFFPUNKT",
    erforderlicheKenntnisse: "ERFORDERLICHE KENNTNISSE",
    verfügbareTermine: "Verfügbare Termine",
    keineTermine: "Keine Termine verfügbar.",
    ausgebucht: "Ausgebucht",
    plaetzeFrei: (n) => `${n} Platz${n !== 1 ? "e" : ""} frei`,
    angemeldet: "✓ Du bist angemeldet",
    terminAendern: "📅 Termin ändern",
    ichMacheMit: "Ich mache mit →",
    anmeldenZumMitmachen: "Anmelden zum Mitmachen →",
    willkommen: "Willkommen!",
    wieNutzen: "Wie möchtest du die App nutzen?",
    binFreiwilliger: "Ich bin Freiwilliger",
    entdeckenAnmelden: "Ehrenamtsstellen entdecken & anmelden",
    binVerein: "Ich bin ein Verein",
    stellenAusschreiben: "Stellen ausschreiben & Freiwillige finden",
    emailBestaetigen: "Email bestätigen!",
    bestaetigungsmail: "Wir haben dir eine Bestätigungsmail geschickt.",
    linkKlicken: "Bitte klick auf den Link bevor du dich anmeldest.",
    zurueckLogin: "Zurück zum Login",
    passwortVergessen: "Passwort vergessen?",
    nochKeinKonto: "Noch kein Konto? Registrieren",
    email: "Email",
    passwort: "Passwort",
    anmeldenBtn: "Anmelden",
    laden: "Laden...",
    registrieren: "🙋 Registrieren",
    vollstaendigerName: "Vollständiger Name (Pflicht)",
    plzWohnort: "PLZ deines Wohnorts",
    faehigkeiten: "FÄHIGKEITEN (optional)",
    sprachen: "🗣️ Sprachen (optional)",
    kontoErstellen: "Konto erstellen",
    vereinRegistrieren: "🏢 Verein registrieren",
    vereinWirdGeprueft: "Dein Verein wird nach Prüfung freigeschaltet.",
    vereinsname: "Name des Vereins",
    ort: "Ort",
    plz: "PLZ",
    antragStellen: "Antrag stellen",
    datenschutzText: "Ich akzeptiere die",
    datenschutzLink: "Datenschutzerklärung",
    und: "und",
    agbLink: "AGB",
    vonCivico: "von Civico.",
    emailPasswortEingeben: "Bitte Email und Passwort eingeben.",
    emailFalsch: "Email oder Passwort falsch!",
    profilNichtGefunden: "Profil nicht gefunden.",
    alleFelder: "Bitte alle Felder ausfüllen.",
    klarname: "Bitte Vor- und Nachname eingeben.",
    passwortLaenge: "Passwort muss mindestens 6 Zeichen haben.",
    datenschutzAkzeptieren: "Bitte Datenschutzerklärung und AGB akzeptieren.",
    emailRegistriert: "Email bereits registriert.",
    keinGemeinde: "Für diese PLZ wurde noch keine Gemeinde gefunden.",
    meinProfil: "Mein Profil",
    einstellungen: "⚙️ Einstellungen",
    punkte: "Punkte",
    medaille: "Medaille",
    aktionen: "Aktionen",
    meineMedaille: "MEINE MEDAILLE",
    naechste: "Nächste:",
    punkteFehlen: "Punkte fehlen",
    hoechsteStufe: "🎉 Höchste Stufe erreicht!",
    meineAktionenVerwalten: "MEINE AKTIONEN VERWALTEN",
    keineAktiveAnmeldungen: "Keine aktiven Anmeldungen.",
    meineAktionen: "MEINE AKTIONEN",
    nochKeineAktionen: "Noch keine Aktionen.",
    punktesystem: "PUNKTESYSTEM",
    einstellungenTitle: "Einstellungen",
    profilTab: "👤 Profil",
    passwortTab: "🔑 Passwort",
    kontoTab: "⚙️ Konto",
    umkreis: "UMKREIS",
    profilSpeichern: "Profil speichern ✓",
    speichern: "Speichern...",
    neuesPasswort: "Neues Passwort",
    passwortWiederholen: "Passwort wiederholen",
    passwortAendern: "Passwort ändern",
    aendern: "Ändern...",
    kontoInfo: "KONTO INFO",
    registriertAls: "Registriert als Freiwilliger",
    rechtliches: "RECHTLICHES",
    kontoLoeschen: "Konto löschen",
    allesWirdGeloescht: "⚠️ Alle deine Daten werden unwiderruflich gelöscht.",
    jaLoeschen: "Ja, löschen",
    abbrechen: "Abbrechen",
    angemeldetPunkte: "✓ Angemeldet! +10 Punkte 🎉",
    ausgebuchtToast: "Leider ausgebucht!",
    fehlerBuchen: "Fehler beim Buchen.",
    abgemeldetPunkte: "Abgemeldet. -10 Punkte",
    fehlerAbmelden: "Fehler beim Abmelden.",
    terminGeaendert: "✓ Termin geändert!",
    erschienen: "✓ Erschienen! +5 Punkte 🎉",
    nichtErschienen: "Nicht erschienen. -15 Punkte",
    profilGespeichert: "✓ Profil gespeichert!",
    passwortGeaendert: "✓ Passwort geändert!",
    neueStelle: "+ Neue Stelle",
    verifizierungAusstehend: "⏳ Verifizierung ausstehend",
    vereinWirdGeprueftMsg: "Dein Verein wird geprüft.",
    deineStellen: "Deine Stellen",
    nochKeineStellen: "Noch keine Stellen",
    ersteStelle: "Erstelle deine erste Ehrenamtsstelle!",
    anmeldungen: "Anmeldungen",
    neueStelleTitel: "Neue Stelle",
    titel: "Titel",
    beschreibung: "BESCHREIBUNG",
    wasErwartet: "Was erwartet die Freiwilligen?",
    typ: "TYP",
    einmaligesEvent: "📅 Einmaliges Event",
    dauerhaft: "🔄 Dauerhaft",
    kategorie: "KATEGORIE",
    zeitaufwand: "Zeitaufwand",
    standort: "Standort / Treffpunkt",
    dringend: "🔴 Als dringend markieren",
    erforderlicheKenntnisseLabel: "ERFORDERLICHE KENNTNISSE (optional)",
    termine: "TERMINE",
    startzeit: "STARTZEIT",
    endzeit: "ENDZEIT (optional)",
    freiePlaetze: "Freie Plätze:",
    stelleVeroeffentlichen: "Stelle veröffentlichen ✓",
    erschienenenBestaetigen: "✓ Erschienen (+5)",
    nichtErschienenenBestaetigen: "✗ Nicht erschienen",
    erschieenenBestaetigt: "✓ Erschienen bestätigt",
    impressum: "Impressum",
    datenschutz: "Datenschutz",
    agb: "AGB",
    neuenTerminWaehlen: "📅 Neuen Termin wählen",
    keineAngaben: "Keine weiteren Angaben.",
    gebuchterTermin: "GEBUCHTER TERMIN",
    faehigkeitenLabel: "FÄHIGKEITEN",
    vereinsprofil: "Vereinsprofil",
    mitglieder: "Mitglieder",
    gegruendet: "Gegründet",
    stelleDetails: "Stelle Details",
    angemeldete: "ANGEMELDETE",
    nochNiemand: "Noch niemand angemeldet.",
    stelleLoeschen: "Stelle löschen",
    analyse: "Analyse",
    gesamtuebersicht: "Gesamtübersicht",
    proStelle: "Pro Stelle",
    nochKeineDaten: "Noch keine Daten",
    stellenErstellen: "Erstelle Stellen um Statistiken zu sehen",
    vereinsname2: "Vereinsname",
    ueberUns: "ÜBER UNS",
    beschreibtEuch: "Beschreibt euren Verein...",
    speichernBtn: "Speichern ✓",
    passwortMindestp: "🔒 Mindestens 6 Zeichen.",
    fehlerSpeichern: "Fehler beim Speichern.",
    fehlerPasswort: "Fehler. Bitte neu einloggen.",
    passwortStimmenNicht: "Passwörter stimmen nicht überein.",
    resetLinkSenden: "Reset-Link senden",
    senden: "Senden...",
    resetGesendet: "✓ Reset-Link gesendet!",
    freiwilligenProfil: "Freiwilligen-Profil",
    ueber: "Über uns",
    aktuelleAktionen: "Aktuelle Aktionen",
    fotoHochladen: "📷 Foto hochladen",
    fotoAendern: "📷 Foto ändern",
    ansprechpartner: "Ansprechpartner",
    kontaktEmail: "Kontakt-Email",
    anmeldungLabel: "Anmeldung",
  },
  en: {
    flag: "🇬🇧",
    name: "English",
    anmelden: "Login →",
    profil: "Profile",
    dashboard: "Dashboard",
    abmelden: "Logout",
    plzOrt: "Postal Code or City",
    alle: "All",
    stellenGefunden: (n) => `${n} positions found`,
    keineStellen: "No positions found",
    filterAendern: "Change filter or postal code",
    zurueck: "← Back",
    home: "Home",
    aufrufe: (n) => `${n} views`,
    treffpunkt: "MEETING POINT",
    erforderlicheKenntnisse: "REQUIRED SKILLS",
    verfügbareTermine: "Available Dates",
    keineTermine: "No dates available.",
    ausgebucht: "Fully booked",
    plaetzeFrei: (n) => `${n} spot${n !== 1 ? "s" : ""} free`,
    angemeldet: "✓ You are registered",
    terminAendern: "📅 Change Date",
    ichMacheMit: "I'm in →",
    anmeldenZumMitmachen: "Login to join →",
    willkommen: "Welcome!",
    wieNutzen: "How would you like to use the app?",
    binFreiwilliger: "I'm a Volunteer",
    entdeckenAnmelden: "Discover & sign up for volunteering",
    binVerein: "I'm an Organisation",
    stellenAusschreiben: "Post positions & find volunteers",
    emailBestaetigen: "Confirm your email!",
    bestaetigungsmail: "We sent you a confirmation email.",
    linkKlicken: "Please click the link before logging in.",
    zurueckLogin: "Back to Login",
    passwortVergessen: "Forgot password?",
    nochKeinKonto: "No account? Register",
    email: "Email",
    passwort: "Password",
    anmeldenBtn: "Login",
    laden: "Loading...",
    registrieren: "🙋 Register",
    vollstaendigerName: "Full Name (Required)",
    plzWohnort: "Your Postal Code",
    faehigkeiten: "YOUR SKILLS (optional)",
    sprachen: "🗣️ Languages (optional)",
    kontoErstellen: "Create Account",
    vereinRegistrieren: "🏢 Register Organisation",
    vereinWirdGeprueft: "Your organisation will be activated after review.",
    vereinsname: "Organisation Name",
    ort: "City",
    plz: "Postal Code",
    antragStellen: "Apply",
    datenschutzText: "I accept the",
    datenschutzLink: "Privacy Policy",
    und: "and",
    agbLink: "Terms",
    vonCivico: "of Civico.",
    emailPasswortEingeben: "Please enter email and password.",
    emailFalsch: "Wrong email or password!",
    profilNichtGefunden: "Profile not found.",
    alleFelder: "Please fill in all fields.",
    klarname: "Please enter first and last name.",
    passwortLaenge: "Password must be at least 6 characters.",
    datenschutzAkzeptieren: "Please accept privacy policy and terms.",
    emailRegistriert: "Email already registered.",
    keinGemeinde: "No municipality found for this postal code.",
    meinProfil: "My Profile",
    einstellungen: "⚙️ Settings",
    punkte: "Points",
    medaille: "Medal",
    aktionen: "Actions",
    meineMedaille: "MY MEDAL",
    naechste: "Next:",
    punkteFehlen: "points needed",
    hoechsteStufe: "🎉 Highest level reached!",
    meineAktionenVerwalten: "MANAGE MY ACTIVITIES",
    keineAktiveAnmeldungen: "No active registrations.",
    meineAktionen: "MY ACTIVITIES",
    nochKeineAktionen: "No activities yet.",
    punktesystem: "POINTS SYSTEM",
    einstellungenTitle: "Settings",
    profilTab: "👤 Profile",
    passwortTab: "🔑 Password",
    kontoTab: "⚙️ Account",
    umkreis: "RADIUS",
    profilSpeichern: "Save Profile ✓",
    speichern: "Saving...",
    neuesPasswort: "New Password",
    passwortWiederholen: "Repeat Password",
    passwortAendern: "Change Password",
    aendern: "Changing...",
    kontoInfo: "ACCOUNT INFO",
    registriertAls: "Registered as Volunteer",
    rechtliches: "LEGAL",
    kontoLoeschen: "Delete Account",
    allesWirdGeloescht: "⚠️ All your data will be permanently deleted.",
    jaLoeschen: "Yes, Delete",
    abbrechen: "Cancel",
    angemeldetPunkte: "✓ Registered! +10 Points 🎉",
    ausgebuchtToast: "Sorry, fully booked!",
    fehlerBuchen: "Error while booking.",
    abgemeldetPunkte: "Unregistered. -10 Points",
    fehlerAbmelden: "Error while unregistering.",
    terminGeaendert: "✓ Date changed!",
    erschienen: "✓ Attended! +5 Points 🎉",
    nichtErschienen: "Did not attend. -15 Points",
    profilGespeichert: "✓ Profile saved!",
    passwortGeaendert: "✓ Password changed!",
    neueStelle: "+ New Position",
    verifizierungAusstehend: "⏳ Verification Pending",
    vereinWirdGeprueftMsg: "Your organisation is being reviewed.",
    deineStellen: "Your Positions",
    nochKeineStellen: "No positions yet",
    ersteStelle: "Create your first volunteering position!",
    anmeldungen: "Registrations",
    neueStelleTitel: "New Position",
    titel: "Title",
    beschreibung: "DESCRIPTION",
    wasErwartet: "What should volunteers expect?",
    typ: "TYPE",
    einmaligesEvent: "📅 One-time Event",
    dauerhaft: "🔄 Ongoing",
    kategorie: "CATEGORY",
    zeitaufwand: "Time Required",
    standort: "Meeting Point",
    dringend: "🔴 Mark as urgent",
    erforderlicheKenntnisseLabel: "REQUIRED SKILLS (optional)",
    termine: "DATES",
    startzeit: "START TIME",
    endzeit: "END TIME (optional)",
    freiePlaetze: "Free spots:",
    stelleVeroeffentlichen: "Publish Position ✓",
    erschienenenBestaetigen: "✓ Attended (+5)",
    nichtErschienenenBestaetigen: "✗ Did not attend",
    erschieenenBestaetigt: "✓ Attendance confirmed",
    impressum: "Imprint",
    datenschutz: "Privacy",
    agb: "Terms",
    neuenTerminWaehlen: "📅 Choose New Date",
    keineAngaben: "No further details.",
    gebuchterTermin: "BOOKED DATE",
    faehigkeitenLabel: "SKILLS",
    vereinsprofil: "Organisation Profile",
    mitglieder: "Members",
    gegruendet: "Founded",
    stelleDetails: "Position Details",
    angemeldete: "REGISTERED",
    nochNiemand: "Nobody registered yet.",
    stelleLoeschen: "Delete Position",
    analyse: "Analysis",
    gesamtuebersicht: "Overview",
    proStelle: "Per Position",
    nochKeineDaten: "No data yet",
    stellenErstellen: "Create positions to see statistics",
    vereinsname2: "Organisation Name",
    ueberUns: "ABOUT US",
    beschreibtEuch: "Describe your organisation...",
    speichernBtn: "Save ✓",
    passwortMindestp: "🔒 At least 6 characters.",
    fehlerSpeichern: "Error saving.",
    fehlerPasswort: "Error. Please log in again.",
    passwortStimmenNicht: "Passwords do not match.",
    resetLinkSenden: "Send Reset Link",
    senden: "Sending...",
    resetGesendet: "✓ Reset link sent!",
    freiwilligenProfil: "Volunteer Profile",
    ueber: "About us",
    aktuelleAktionen: "Current Activities",
    fotoHochladen: "📷 Upload Photo",
    fotoAendern: "📷 Change Photo",
    ansprechpartner: "Contact Person",
    kontaktEmail: "Contact Email",
    anmeldungLabel: "Registration",
  },
  tr: {
    flag: "🇹🇷",
    name: "Türkçe",
    anmelden: "Giriş →",
    profil: "Profil",
    dashboard: "Panel",
    abmelden: "Çıkış",
    plzOrt: "Posta Kodu veya Şehir",
    alle: "Tümü",
    stellenGefunden: (n) => `${n} pozisyon bulundu`,
    keineStellen: "Pozisyon bulunamadı",
    filterAendern: "Filtreyi değiştirin",
    zurueck: "← Geri",
    home: "Ana Sayfa",
    aufrufe: (n) => `${n} görüntüleme`,
    treffpunkt: "BULUŞMA YERİ",
    erforderlicheKenntnisse: "GEREKLİ BİLGİLER",
    verfügbareTermine: "Uygun Tarihler",
    keineTermine: "Uygun tarih yok.",
    ausgebucht: "Dolu",
    plaetzeFrei: (n) => `${n} yer boş`,
    angemeldet: "✓ Kayıtlısın",
    terminAendern: "📅 Tarihi Değiştir",
    ichMacheMit: "Katılıyorum →",
    anmeldenZumMitmachen: "Katılmak için giriş yap →",
    willkommen: "Hoş Geldiniz!",
    wieNutzen: "Uygulamayı nasıl kullanmak istersiniz?",
    binFreiwilliger: "Gönüllüyüm",
    entdeckenAnmelden: "Gönüllülük pozisyonlarını keşfet",
    binVerein: "Bir Dernegim",
    stellenAusschreiben: "Pozisyon yayınla ve gönüllü bul",
    emailBestaetigen: "E-postayı onayla!",
    bestaetigungsmail: "Onay e-postası gönderdik.",
    linkKlicken: "Giriş yapmadan önce linke tıklayın.",
    zurueckLogin: "Girişe Dön",
    passwortVergessen: "Şifremi unuttum?",
    nochKeinKonto: "Hesabın yok mu? Kayıt ol",
    email: "E-posta",
    passwort: "Şifre",
    anmeldenBtn: "Giriş Yap",
    laden: "Yükleniyor...",
    registrieren: "🙋 Kayıt Ol",
    vollstaendigerName: "Ad Soyad (Zorunlu)",
    plzWohnort: "Posta Kodunuz",
    faehigkeiten: "YETENEKLERİNİZ (isteğe bağlı)",
    sprachen: "🗣️ Diller (isteğe bağlı)",
    kontoErstellen: "Hesap Oluştur",
    vereinRegistrieren: "🏢 Dernek Kaydı",
    vereinWirdGeprueft: "Derneğiniz incelendikten sonra aktif edilecektir.",
    vereinsname: "Dernek Adı",
    ort: "Şehir",
    plz: "Posta Kodu",
    antragStellen: "Başvur",
    datenschutzText: "Kabul ediyorum:",
    datenschutzLink: "Gizlilik Politikası",
    und: "ve",
    agbLink: "Kullanım Şartları",
    vonCivico: "Civico'nun",
    emailPasswortEingeben: "Lütfen e-posta ve şifre girin.",
    emailFalsch: "E-posta veya şifre yanlış!",
    profilNichtGefunden: "Profil bulunamadı.",
    alleFelder: "Lütfen tüm alanları doldurun.",
    klarname: "Lütfen ad ve soyadınızı girin.",
    passwortLaenge: "Şifre en az 6 karakter olmalı.",
    datenschutzAkzeptieren: "Lütfen gizlilik politikasını kabul edin.",
    emailRegistriert: "E-posta zaten kayıtlı.",
    keinGemeinde: "Bu posta kodu için belediye bulunamadı.",
    meinProfil: "Profilim",
    einstellungen: "⚙️ Ayarlar",
    punkte: "Puan",
    medaille: "Madalya",
    aktionen: "Eylemler",
    meineMedaille: "MADALYAm",
    naechste: "Sonraki:",
    punkteFehlen: "puan eksik",
    hoechsteStufe: "🎉 En yüksek seviye!",
    meineAktionenVerwalten: "AKTİF ETKİNLİKLERİM",
    keineAktiveAnmeldungen: "Aktif kayıt yok.",
    meineAktionen: "ETKİNLİKLERİM",
    nochKeineAktionen: "Henüz etkinlik yok.",
    punktesystem: "PUAN SİSTEMİ",
    einstellungenTitle: "Ayarlar",
    profilTab: "👤 Profil",
    passwortTab: "🔑 Şifre",
    kontoTab: "⚙️ Hesap",
    umkreis: "MESAFE",
    profilSpeichern: "Profili Kaydet ✓",
    speichern: "Kaydediliyor...",
    neuesPasswort: "Yeni Şifre",
    passwortWiederholen: "Şifreyi Tekrarla",
    passwortAendern: "Şifreyi Değiştir",
    aendern: "Değiştiriliyor...",
    kontoInfo: "HESAP BİLGİSİ",
    registriertAls: "Gönüllü olarak kayıtlı",
    rechtliches: "YASAL",
    kontoLoeschen: "Hesabı Sil",
    allesWirdGeloescht: "⚠️ Tüm verileriniz kalıcı olarak silinecek.",
    jaLoeschen: "Evet, Sil",
    abbrechen: "İptal",
    angemeldetPunkte: "✓ Kayıt olundu! +10 Puan 🎉",
    ausgebuchtToast: "Maalesef dolu!",
    fehlerBuchen: "Kayıt hatası.",
    abgemeldetPunkte: "İptal edildi. -10 Puan",
    fehlerAbmelden: "İptal hatası.",
    terminGeaendert: "✓ Tarih değiştirildi!",
    erschienen: "✓ Katıldı! +5 Puan 🎉",
    nichtErschienen: "Katılmadı. -15 Puan",
    profilGespeichert: "✓ Profil kaydedildi!",
    passwortGeaendert: "✓ Şifre değiştirildi!",
    neueStelle: "+ Yeni Pozisyon",
    verifizierungAusstehend: "⏳ Onay Bekleniyor",
    vereinWirdGeprueftMsg: "Derneğiniz inceleniyor.",
    deineStellen: "Pozisyonlarınız",
    nochKeineStellen: "Henüz pozisyon yok",
    ersteStelle: "İlk pozisyonunuzu oluşturun!",
    anmeldungen: "Kayıt",
    neueStelleTitel: "Yeni Pozisyon",
    titel: "Başlık",
    beschreibung: "AÇIKLAMA",
    wasErwartet: "Gönüllüler ne beklemeli?",
    typ: "TİP",
    einmaligesEvent: "📅 Tek Seferlik",
    dauerhaft: "🔄 Sürekli",
    kategorie: "KATEGORİ",
    zeitaufwand: "Zaman",
    standort: "Buluşma Yeri",
    dringend: "🔴 Acil olarak işaretle",
    erforderlicheKenntnisseLabel: "GEREKLİ BİLGİLER (isteğe bağlı)",
    termine: "TARİHLER",
    startzeit: "BAŞLANGIÇ",
    endzeit: "BİTİŞ (isteğe bağlı)",
    freiePlaetze: "Boş Yer:",
    stelleVeroeffentlichen: "Yayınla ✓",
    erschienenenBestaetigen: "✓ Katıldı (+5)",
    nichtErschienenenBestaetigen: "✗ Katılmadı",
    erschieenenBestaetigt: "✓ Katılım onaylandı",
    impressum: "Künye",
    datenschutz: "Gizlilik",
    agb: "Şartlar",
    neuenTerminWaehlen: "📅 Yeni Tarih Seç",
    keineAngaben: "Başka bilgi yok.",
    gebuchterTermin: "KAYITLI TARİH",
    faehigkeitenLabel: "YETENEKLERİ",
    vereinsprofil: "Dernek Profili",
    mitglieder: "Üyeler",
    gegruendet: "Kuruluş",
    stelleDetails: "Pozisyon Detayları",
    angemeldete: "KAYITLILAR",
    nochNiemand: "Henüz kimse yok.",
    stelleLoeschen: "Pozisyonu Sil",
    analyse: "Analiz",
    gesamtuebersicht: "Genel Bakış",
    proStelle: "Pozisyon Başına",
    nochKeineDaten: "Henüz veri yok",
    stellenErstellen: "Pozisyon ekleyin",
    vereinsname2: "Dernek Adı",
    ueberUns: "HAKKIMIZDA",
    beschreibtEuch: "Derneğinizi tanıtın...",
    speichernBtn: "Kaydet ✓",
    passwortMindestp: "🔒 En az 6 karakter.",
    fehlerSpeichern: "Kaydetme hatası.",
    fehlerPasswort: "Hata. Tekrar giriş yapın.",
    passwortStimmenNicht: "Şifreler eşleşmiyor.",
    resetLinkSenden: "Sıfırlama Linki Gönder",
    senden: "Gönderiliyor...",
    resetGesendet: "✓ Link gönderildi!",
    freiwilligenProfil: "Gönüllü Profili",
    ueber: "Hakkımızda",
    aktuelleAktionen: "Güncel Etkinlikler",
    fotoHochladen: "📷 Fotoğraf yükle",
    fotoAendern: "📷 Fotoğrafı değiştir",
    ansprechpartner: "İletişim Kişisi",
    kontaktEmail: "İletişim E-postası",
    anmeldungLabel: "Kayıt",
  },
  ru: {
    flag: "🇷🇺",
    name: "Русский",
    anmelden: "Войти →",
    profil: "Профиль",
    dashboard: "Панель",
    abmelden: "Выйти",
    plzOrt: "Индекс или город",
    alle: "Все",
    stellenGefunden: (n) => `Найдено ${n} вакансий`,
    keineStellen: "Вакансии не найдены",
    filterAendern: "Измените фильтр",
    zurueck: "← Назад",
    home: "Главная",
    aufrufe: (n) => `${n} просмотров`,
    treffpunkt: "МЕСТО ВСТРЕЧИ",
    erforderlicheKenntnisse: "ТРЕБУЕМЫЕ НАВЫКИ",
    verfügbareTermine: "Доступные даты",
    keineTermine: "Дат нет.",
    ausgebucht: "Мест нет",
    plaetzeFrei: (n) => `${n} мест свободно`,
    angemeldet: "✓ Вы зарегистрированы",
    terminAendern: "📅 Изменить дату",
    ichMacheMit: "Участвую →",
    anmeldenZumMitmachen: "Войдите чтобы участвовать →",
    willkommen: "Добро пожаловать!",
    wieNutzen: "Как вы хотите использовать приложение?",
    binFreiwilliger: "Я волонтёр",
    entdeckenAnmelden: "Найти волонтёрство",
    binVerein: "Я организация",
    stellenAusschreiben: "Публикуйте вакансии",
    emailBestaetigen: "Подтвердите email!",
    bestaetigungsmail: "Мы отправили письмо.",
    linkKlicken: "Нажмите на ссылку перед входом.",
    zurueckLogin: "Вернуться к входу",
    passwortVergessen: "Забыли пароль?",
    nochKeinKonto: "Нет аккаунта? Зарегистрируйтесь",
    email: "Email",
    passwort: "Пароль",
    anmeldenBtn: "Войти",
    laden: "Загрузка...",
    registrieren: "🙋 Регистрация",
    vollstaendigerName: "Полное имя (обязательно)",
    plzWohnort: "Почтовый индекс",
    faehigkeiten: "НАВЫКИ (необязательно)",
    sprachen: "🗣️ Языки (необязательно)",
    kontoErstellen: "Создать аккаунт",
    vereinRegistrieren: "🏢 Зарегистрировать организацию",
    vereinWirdGeprueft: "Организация будет активирована после проверки.",
    vereinsname: "Название организации",
    ort: "Город",
    plz: "Индекс",
    antragStellen: "Подать заявку",
    datenschutzText: "Я принимаю",
    datenschutzLink: "Политику конфиденциальности",
    und: "и",
    agbLink: "Условия",
    vonCivico: "Civico.",
    emailPasswortEingeben: "Введите email и пароль.",
    emailFalsch: "Неверный email или пароль!",
    profilNichtGefunden: "Профиль не найден.",
    alleFelder: "Заполните все поля.",
    klarname: "Введите имя и фамилию.",
    passwortLaenge: "Пароль не менее 6 символов.",
    datenschutzAkzeptieren: "Примите политику.",
    emailRegistriert: "Email уже зарегистрирован.",
    keinGemeinde: "Муниципалитет не найден.",
    meinProfil: "Мой профиль",
    einstellungen: "⚙️ Настройки",
    punkte: "Очки",
    medaille: "Медаль",
    aktionen: "Действия",
    meineMedaille: "МОЯ МЕДАЛЬ",
    naechste: "Следующая:",
    punkteFehlen: "очков не хватает",
    hoechsteStufe: "🎉 Высший уровень!",
    meineAktionenVerwalten: "МОИ АКТИВНЫЕ ЗАПИСИ",
    keineAktiveAnmeldungen: "Нет активных записей.",
    meineAktionen: "МОИ ДЕЙСТВИЯ",
    nochKeineAktionen: "Действий пока нет.",
    punktesystem: "СИСТЕМА ОЧКОВ",
    einstellungenTitle: "Настройки",
    profilTab: "👤 Профиль",
    passwortTab: "🔑 Пароль",
    kontoTab: "⚙️ Аккаунт",
    umkreis: "РАДИУС",
    profilSpeichern: "Сохранить ✓",
    speichern: "Сохранение...",
    neuesPasswort: "Новый пароль",
    passwortWiederholen: "Повторите пароль",
    passwortAendern: "Изменить пароль",
    aendern: "Изменение...",
    kontoInfo: "ИНФОРМАЦИЯ",
    registriertAls: "Зарегистрирован как волонтёр",
    rechtliches: "ПРАВОВОЕ",
    kontoLoeschen: "Удалить аккаунт",
    allesWirdGeloescht: "⚠️ Все данные будут удалены.",
    jaLoeschen: "Да, удалить",
    abbrechen: "Отмена",
    angemeldetPunkte: "✓ Записан! +10 очков 🎉",
    ausgebuchtToast: "Мест нет!",
    fehlerBuchen: "Ошибка записи.",
    abgemeldetPunkte: "Отменено. -10 очков",
    fehlerAbmelden: "Ошибка отмены.",
    terminGeaendert: "✓ Дата изменена!",
    erschienen: "✓ Присутствовал! +5 🎉",
    nichtErschienen: "Не явился. -15 очков",
    profilGespeichert: "✓ Профиль сохранён!",
    passwortGeaendert: "✓ Пароль изменён!",
    neueStelle: "+ Новая вакансия",
    verifizierungAusstehend: "⏳ Ожидает проверки",
    vereinWirdGeprueftMsg: "Организация проверяется.",
    deineStellen: "Ваши вакансии",
    nochKeineStellen: "Вакансий нет",
    ersteStelle: "Создайте первую вакансию!",
    anmeldungen: "Записей",
    neueStelleTitel: "Новая вакансия",
    titel: "Заголовок",
    beschreibung: "ОПИСАНИЕ",
    wasErwartet: "Что ждёт волонтёров?",
    typ: "ТИП",
    einmaligesEvent: "📅 Разовое",
    dauerhaft: "🔄 Постоянное",
    kategorie: "КАТЕГОРИЯ",
    zeitaufwand: "Время",
    standort: "Место встречи",
    dringend: "🔴 Срочно",
    erforderlicheKenntnisseLabel: "НАВЫКИ (необязательно)",
    termine: "ДАТЫ",
    startzeit: "НАЧАЛО",
    endzeit: "КОНЕЦ (необязательно)",
    freiePlaetze: "Мест:",
    stelleVeroeffentlichen: "Опубликовать ✓",
    erschienenenBestaetigen: "✓ Присутствовал (+5)",
    nichtErschienenenBestaetigen: "✗ Не явился",
    erschieenenBestaetigt: "✓ Подтверждено",
    impressum: "Импрессум",
    datenschutz: "Конфид.",
    agb: "Условия",
    neuenTerminWaehlen: "📅 Выбрать дату",
    keineAngaben: "Нет данных.",
    gebuchterTermin: "ДАТА",
    faehigkeitenLabel: "НАВЫКИ",
    vereinsprofil: "Профиль организации",
    mitglieder: "Членов",
    gegruendet: "Основана",
    stelleDetails: "Детали",
    angemeldete: "ЗАПИСАНЫ",
    nochNiemand: "Никто не записался.",
    stelleLoeschen: "Удалить",
    analyse: "Анализ",
    gesamtuebersicht: "Обзор",
    proStelle: "По вакансии",
    nochKeineDaten: "Данных нет",
    stellenErstellen: "Добавьте вакансии",
    vereinsname2: "Название",
    ueberUns: "О НАС",
    beschreibtEuch: "Опишите организацию...",
    speichernBtn: "Сохранить ✓",
    passwortMindestp: "🔒 Не менее 6 символов.",
    fehlerSpeichern: "Ошибка.",
    fehlerPasswort: "Ошибка. Войдите снова.",
    passwortStimmenNicht: "Пароли не совпадают.",
    resetLinkSenden: "Отправить ссылку",
    senden: "Отправка...",
    resetGesendet: "✓ Ссылка отправлена!",
    freiwilligenProfil: "Профиль волонтёра",
    ueber: "О нас",
    aktuelleAktionen: "Мероприятия",
    fotoHochladen: "📷 Загрузить фото",
    fotoAendern: "📷 Изменить фото",
    ansprechpartner: "Контактное лицо",
    kontaktEmail: "Контактный Email",
    anmeldungLabel: "Регистрация",
  },
  pl: {
    flag: "🇵🇱",
    name: "Polski",
    anmelden: "Zaloguj →",
    profil: "Profil",
    dashboard: "Panel",
    abmelden: "Wyloguj",
    plzOrt: "Kod pocztowy lub miasto",
    alle: "Wszystkie",
    stellenGefunden: (n) => `Znaleziono ${n} ofert`,
    keineStellen: "Nie znaleziono ofert",
    filterAendern: "Zmień filtr",
    zurueck: "← Wstecz",
    home: "Strona główna",
    aufrufe: (n) => `${n} wyświetleń`,
    treffpunkt: "MIEJSCE SPOTKANIA",
    erforderlicheKenntnisse: "WYMAGANE UMIEJĘTNOŚCI",
    verfügbareTermine: "Dostępne terminy",
    keineTermine: "Brak terminów.",
    ausgebucht: "Brak miejsc",
    plaetzeFrei: (n) => `${n} miejsc wolnych`,
    angemeldet: "✓ Jesteś zapisany",
    terminAendern: "📅 Zmień termin",
    ichMacheMit: "Biorę udział →",
    anmeldenZumMitmachen: "Zaloguj się by wziąć udział →",
    willkommen: "Witamy!",
    wieNutzen: "Jak chcesz korzystać z aplikacji?",
    binFreiwilliger: "Jestem wolontariuszem",
    entdeckenAnmelden: "Odkryj wolontariat",
    binVerein: "Jestem organizacją",
    stellenAusschreiben: "Publikuj oferty",
    emailBestaetigen: "Potwierdź email!",
    bestaetigungsmail: "Wysłaliśmy email.",
    linkKlicken: "Kliknij link przed zalogowaniem.",
    zurueckLogin: "Powrót do logowania",
    passwortVergessen: "Zapomniałeś hasła?",
    nochKeinKonto: "Brak konta? Zarejestruj się",
    email: "Email",
    passwort: "Hasło",
    anmeldenBtn: "Zaloguj",
    laden: "Ładowanie...",
    registrieren: "🙋 Rejestracja",
    vollstaendigerName: "Imię i nazwisko (wymagane)",
    plzWohnort: "Twój kod pocztowy",
    faehigkeiten: "UMIEJĘTNOŚCI (opcjonalnie)",
    sprachen: "🗣️ Języki (opcjonalnie)",
    kontoErstellen: "Utwórz konto",
    vereinRegistrieren: "🏢 Zarejestruj organizację",
    vereinWirdGeprueft: "Organizacja zostanie aktywowana po weryfikacji.",
    vereinsname: "Nazwa organizacji",
    ort: "Miasto",
    plz: "Kod pocztowy",
    antragStellen: "Aplikuj",
    datenschutzText: "Akceptuję",
    datenschutzLink: "Politykę prywatności",
    und: "i",
    agbLink: "Regulamin",
    vonCivico: "Civico.",
    emailPasswortEingeben: "Podaj email i hasło.",
    emailFalsch: "Błędny email lub hasło!",
    profilNichtGefunden: "Profil nie znaleziony.",
    alleFelder: "Wypełnij wszystkie pola.",
    klarname: "Podaj imię i nazwisko.",
    passwortLaenge: "Hasło min. 6 znaków.",
    datenschutzAkzeptieren: "Zaakceptuj politykę.",
    emailRegistriert: "Email już zarejestrowany.",
    keinGemeinde: "Nie znaleziono gminy.",
    meinProfil: "Mój profil",
    einstellungen: "⚙️ Ustawienia",
    punkte: "Punkty",
    medaille: "Medal",
    aktionen: "Działania",
    meineMedaille: "MÓJ MEDAL",
    naechste: "Następny:",
    punkteFehlen: "punktów brakuje",
    hoechsteStufe: "🎉 Najwyższy poziom!",
    meineAktionenVerwalten: "MOJE AKTYWNE ZAPISY",
    keineAktiveAnmeldungen: "Brak aktywnych zapisów.",
    meineAktionen: "MOJE DZIAŁANIA",
    nochKeineAktionen: "Brak działań.",
    punktesystem: "SYSTEM PUNKTÓW",
    einstellungenTitle: "Ustawienia",
    profilTab: "👤 Profil",
    passwortTab: "🔑 Hasło",
    kontoTab: "⚙️ Konto",
    umkreis: "PROMIEŃ",
    profilSpeichern: "Zapisz profil ✓",
    speichern: "Zapisywanie...",
    neuesPasswort: "Nowe hasło",
    passwortWiederholen: "Powtórz hasło",
    passwortAendern: "Zmień hasło",
    aendern: "Zmiana...",
    kontoInfo: "INFORMACJE",
    registriertAls: "Zarejestrowany jako wolontariusz",
    rechtliches: "PRAWNE",
    kontoLoeschen: "Usuń konto",
    allesWirdGeloescht: "⚠️ Wszystkie dane zostaną usunięte.",
    jaLoeschen: "Tak, usuń",
    abbrechen: "Anuluj",
    angemeldetPunkte: "✓ Zapisano! +10 punktów 🎉",
    ausgebuchtToast: "Brak miejsc!",
    fehlerBuchen: "Błąd zapisu.",
    abgemeldetPunkte: "Wypisano. -10 punktów",
    fehlerAbmelden: "Błąd wypisania.",
    terminGeaendert: "✓ Termin zmieniony!",
    erschienen: "✓ Uczestniczył! +5 🎉",
    nichtErschienen: "Nie uczestniczył. -15",
    profilGespeichert: "✓ Profil zapisany!",
    passwortGeaendert: "✓ Hasło zmienione!",
    neueStelle: "+ Nowa oferta",
    verifizierungAusstehend: "⏳ Oczekuje weryfikacji",
    vereinWirdGeprueftMsg: "Organizacja jest weryfikowana.",
    deineStellen: "Twoje oferty",
    nochKeineStellen: "Brak ofert",
    ersteStelle: "Utwórz pierwszą ofertę!",
    anmeldungen: "Zapisów",
    neueStelleTitel: "Nowa oferta",
    titel: "Tytuł",
    beschreibung: "OPIS",
    wasErwartet: "Czego oczekiwać?",
    typ: "TYP",
    einmaligesEvent: "📅 Jednorazowe",
    dauerhaft: "🔄 Stałe",
    kategorie: "KATEGORIA",
    zeitaufwand: "Czas",
    standort: "Miejsce spotkania",
    dringend: "🔴 Pilne",
    erforderlicheKenntnisseLabel: "UMIEJĘTNOŚCI (opcjonalnie)",
    termine: "TERMINY",
    startzeit: "POCZĄTEK",
    endzeit: "KONIEC (opcjonalnie)",
    freiePlaetze: "Miejsc:",
    stelleVeroeffentlichen: "Opublikuj ✓",
    erschienenenBestaetigen: "✓ Uczestniczył (+5)",
    nichtErschienenenBestaetigen: "✗ Nie uczestniczył",
    erschieenenBestaetigt: "✓ Potwierdzone",
    impressum: "Impressum",
    datenschutz: "Prywatność",
    agb: "Regulamin",
    neuenTerminWaehlen: "📅 Wybierz termin",
    keineAngaben: "Brak danych.",
    gebuchterTermin: "TERMIN",
    faehigkeitenLabel: "UMIEJĘTNOŚCI",
    vereinsprofil: "Profil organizacji",
    mitglieder: "Członków",
    gegruendet: "Założona",
    stelleDetails: "Szczegóły",
    angemeldete: "ZAPISANI",
    nochNiemand: "Nikt nie zapisał się.",
    stelleLoeschen: "Usuń ofertę",
    analyse: "Analiza",
    gesamtuebersicht: "Przegląd",
    proStelle: "Na ofertę",
    nochKeineDaten: "Brak danych",
    stellenErstellen: "Dodaj oferty",
    vereinsname2: "Nazwa",
    ueberUns: "O NAS",
    beschreibtEuch: "Opisz organizację...",
    speichernBtn: "Zapisz ✓",
    passwortMindestp: "🔒 Min. 6 znaków.",
    fehlerSpeichern: "Błąd.",
    fehlerPasswort: "Błąd. Zaloguj ponownie.",
    passwortStimmenNicht: "Hasła nie pasują.",
    resetLinkSenden: "Wyślij link",
    senden: "Wysyłanie...",
    resetGesendet: "✓ Link wysłany!",
    freiwilligenProfil: "Profil wolontariusza",
    ueber: "O nas",
    aktuelleAktionen: "Aktualne działania",
    fotoHochladen: "📷 Prześlij zdjęcie",
    fotoAendern: "📷 Zmień zdjęcie",
    ansprechpartner: "Osoba kontaktowa",
    kontaktEmail: "Email kontaktowy",
    anmeldungLabel: "Rejestracja",
  },
};

// ── Constants ──────────────────────────────────────────────────────────────
const KATEGORIEN = [
  { id: "sozial", label: "Soziales", icon: "🤝", color: "#E8A87C" },
  { id: "umwelt", label: "Umwelt", icon: "🌱", color: "#6BAF7A" },
  { id: "sport", label: "Sport", icon: "⚽", color: "#5B9BD5" },
  { id: "kultur", label: "Kultur", icon: "🎨", color: "#B07EC4" },
  { id: "bildung", label: "Bildung", icon: "📚", color: "#E8C84A" },
  { id: "feuerwehr", label: "Feuerwehr", icon: "🚒", color: "#E85C5C" },
  { id: "senioren", label: "Senioren", icon: "👴", color: "#8B7355" },
  { id: "tiere", label: "Tierschutz", icon: "🐾", color: "#A0522D" },
];

const SKILLS = [
  { id: "auto", icon: "🚗", label: "Autofahren" },
  { id: "garten", icon: "🌱", label: "Gartenarbeit" },
  { id: "kinder", icon: "👶", label: "Kinderbetreuung" },
  { id: "handwerk", icon: "🔧", label: "Handwerk" },
  { id: "organisation", icon: "📋", label: "Organisation" },
  { id: "erstehilfe", icon: "🏥", label: "Erste Hilfe" },
  { id: "kochen", icon: "🍳", label: "Kochen" },
  { id: "computer", icon: "💻", label: "Computer" },
  { id: "musik", icon: "🎵", label: "Musik" },
  { id: "tiere", icon: "🐾", label: "Tiere" },
  { id: "sport", icon: "⚽", label: "Sport" },
  { id: "foto", icon: "📷", label: "Fotografie" },
];

const SKILLS_LABELS = {
  auto: {
    de: "Autofahren",
    en: "Driving",
    tr: "Araba kullanma",
    ru: "Вождение",
    pl: "Jazda samochodem",
  },
  garten: {
    de: "Gartenarbeit",
    en: "Gardening",
    tr: "Bahçe işleri",
    ru: "Садоводство",
    pl: "Ogrodnictwo",
  },
  kinder: {
    de: "Kinderbetreuung",
    en: "Childcare",
    tr: "Çocuk bakımı",
    ru: "Уход за детьми",
    pl: "Opieka nad dziećmi",
  },
  handwerk: {
    de: "Handwerk",
    en: "Crafts",
    tr: "El işi",
    ru: "Ремесло",
    pl: "Rzemiosło",
  },
  organisation: {
    de: "Organisation",
    en: "Organisation",
    tr: "Organizasyon",
    ru: "Организация",
    pl: "Organizacja",
  },
  erstehilfe: {
    de: "Erste Hilfe",
    en: "First Aid",
    tr: "İlk yardım",
    ru: "Первая помощь",
    pl: "Pierwsza pomoc",
  },
  kochen: {
    de: "Kochen",
    en: "Cooking",
    tr: "Yemek pişirme",
    ru: "Готовка",
    pl: "Gotowanie",
  },
  computer: {
    de: "Computer",
    en: "Computer",
    tr: "Bilgisayar",
    ru: "Компьютер",
    pl: "Komputer",
  },
  musik: { de: "Musik", en: "Music", tr: "Müzik", ru: "Музыка", pl: "Muzyka" },
  tiere: {
    de: "Tiere",
    en: "Animals",
    tr: "Hayvanlar",
    ru: "Животные",
    pl: "Zwierzęta",
  },
  sport: { de: "Sport", en: "Sport", tr: "Spor", ru: "Спорт", pl: "Sport" },
  foto: {
    de: "Fotografie",
    en: "Photography",
    tr: "Fotoğrafçılık",
    ru: "Фотография",
    pl: "Fotografia",
  },
};
const getSkillLabel = (skill, lang) =>
  SKILLS_LABELS[skill.id]?.[lang] || SKILLS_LABELS[skill.id]?.de || skill.label;

const MEDAILLEN = [
  { punkte: 0, icon: "🌱", nameKey: "neuling", farbe: "#8B7355" },
  { punkte: 50, icon: "🥉", nameKey: "starter", farbe: "#CD7F32" },
  { punkte: 150, icon: "🥈", nameKey: "engagiert", farbe: "#A8A9AD" },
  { punkte: 300, icon: "🥇", nameKey: "zuverlaessig", farbe: "#FFD700" },
  { punkte: 500, icon: "🏅", nameKey: "profi", farbe: "#E8A87C" },
  { punkte: 1000, icon: "🏆", nameKey: "champion", farbe: "#3A7D44" },
];

const MEDAILLEN_NAMEN = {
  neuling: {
    de: "Neuling",
    en: "Newcomer",
    tr: "Yeni Üye",
    ru: "Новичок",
    pl: "Nowicjusz",
  },
  starter: {
    de: "Starter",
    en: "Starter",
    tr: "Başlangıç",
    ru: "Начинающий",
    pl: "Początkujący",
  },
  engagiert: {
    de: "Engagiert",
    en: "Engaged",
    tr: "Aktif",
    ru: "Активный",
    pl: "Zaangażowany",
  },
  zuverlaessig: {
    de: "Zuverlässig",
    en: "Reliable",
    tr: "Güvenilir",
    ru: "Надёжный",
    pl: "Niezawodny",
  },
  profi: {
    de: "Ehrenamts-Profi",
    en: "Volunteer Pro",
    tr: "Gönüllü Uzman",
    ru: "Волонтёр-Про",
    pl: "Ekspert",
  },
  champion: {
    de: "Civico Champion",
    en: "Civico Champion",
    tr: "Civico Şampiyonu",
    ru: "Чемпион Civico",
    pl: "Mistrz Civico",
  },
};
const getMedailleName = (m, lang) => {
  if (m.nameKey)
    return (
      MEDAILLEN_NAMEN[m.nameKey]?.[lang] ||
      MEDAILLEN_NAMEN[m.nameKey]?.de ||
      m.nameKey
    );
  if (typeof m.name === "object") return m.name[lang] || m.name.de || "";
  return "";
};

const IMPRESSUM_TEXT = `Impressum
Angaben gemäß § 5 DDG

Lucas Wimmer / Civico
Rheinstraße 26
64683 Einhausen

Vertreten durch: Lucas Wimmer
Telefon: 0162-6262322
E-Mail: Lucas-wimmer@hotmail.de

Verbraucherstreitbeilegung:
Wir nehmen nicht an Streitbeilegungsverfahren teil.

Haftungsausschluss: Inhalte wurden sorgfältig erstellt. Bei Bekanntwerden von Rechtsverletzungen werden diese umgehend entfernt.

Erstellt mit Impressum-Generator von WebsiteWissen.com, Rechtstext von Kanzlei Hasselbach.`;

const DATENSCHUTZ_TEXT = `Datenschutzerklärung – Civico
Stand: 23. März 2026

Verantwortlicher:
Lucas Wimmer
Rheinstraße 26
64683 Einhausen, Deutschland
E-Mail: Lucas-wimmer@hotmail.de

Verarbeitete Daten:
Wir verarbeiten Name, E-Mail, PLZ sowie Angaben zu Ehrenamtseinsätzen zur Bereitstellung der Civico-Plattform.

Rechtsgrundlagen:
- Einwilligung (Art. 6 Abs. 1 lit. a DSGVO) – bei Registrierung erteilt
- Vertragserfüllung (Art. 6 Abs. 1 lit. b DSGVO)
- Berechtigte Interessen (Art. 6 Abs. 1 lit. f DSGVO)

Datenspeicherung:
Alle Daten werden auf EU-Servern (Supabase, Frankfurt) gespeichert. Keine Weitergabe an Dritte zu Werbezwecken. Keine Tracking-Cookies.

Ihre Rechte (Art. 15–21 DSGVO):
Auskunft, Berichtigung, Löschung (direkt über "Konto löschen"), Einschränkung, Datenübertragbarkeit, Widerspruch.
Kontakt: Lucas-wimmer@hotmail.de

Beschwerderecht: Hessischer Beauftragter für Datenschutz und Informationsfreiheit.

Erstellt mit Datenschutz-Generator.de von Dr. Thomas Schwenke, angepasst für Civico.`;

const AGB_TEXT = `Allgemeine Geschäftsbedingungen – Civico
Stand: 23. März 2026
Anbieter: Lucas Wimmer, Rheinstraße 26, 64683 Einhausen

§ 1 Geltungsbereich
Diese AGB gelten für alle Nutzer der Civico-Plattform – Gemeinden, Vereine und Freiwillige.

§ 2 Leistungsbeschreibung
Civico vermittelt Ehrenamtseinsätze. Für Freiwillige kostenlos. Die Durchführung von Einsätzen liegt in der Verantwortung der Vereine.

§ 3 Nutzerkonto
Wahrheitsgemäße Angaben erforderlich. Ein Konto pro Person. Keine Weitergabe von Zugangsdaten.

§ 4 Pflichten der Nutzer
Keine falschen Angaben. Respektvoller Umgang. Keine rechtswidrigen Inhalte. Verbindliche Einhaltung von Anmeldungen oder rechtzeitige Absage.

§ 5 Punktesystem
Kein monetärer Gegenwert. Nicht übertragbar. Civico kann das System jederzeit anpassen.

§ 6 Haftungsausschluss
Civico haftet nicht für Schäden bei Ehrenamtseinsätzen. Haftung liegt bei den Vereinen.

§ 7 Datenschutz
Verarbeitung gemäß unserer Datenschutzerklärung.

§ 8 Kündigung
Kontolöschung jederzeit über Einstellungen → Konto löschen.

§ 9 Änderungen
Wesentliche Änderungen werden per E-Mail mitgeteilt.

§ 10 Anwendbares Recht
Deutsches Recht. Gerichtsstand Einhausen / Hessen.`;

// ── Helpers ────────────────────────────────────────────────────────────────
const getMedaille = (punkte) => {
  let aktuelle = MEDAILLEN[0];
  for (const m of MEDAILLEN) {
    if (punkte >= m.punkte) aktuelle = m;
  }
  return aktuelle;
};
const getNextMedaille = (punkte) => {
  for (const m of MEDAILLEN) {
    if (punkte < m.punkte) return m;
  }
  return null;
};
const formatDate = (d) =>
  !d
    ? ""
    : new Date(d).toLocaleDateString("de-DE", {
        weekday: "short",
        day: "2-digit",
        month: "2-digit",
      });
const getKat = (id) => KATEGORIEN.find((k) => k.id === id);
const getGemeindeByPlz = async (plz) => {
  if (!plz) return null;
  const { data } = await supabase.rpc("get_gemeinde_by_plz", { p_plz: plz });
  return data || null;
};
const isKlarname = (name) => {
  const parts = name.trim().split(" ");
  if (parts.length < 2) return false;
  return parts.every((p) => p.length >= 2 && /^[a-zA-ZäöüÄÖÜß-]+$/.test(p));
};
const isTerminNochNichtGestartet = (t) => {
  if (!t.datum) return false;
  // Parse date parts explicitly to avoid timezone issues
  const [year, month, day] = t.datum.split("-").map(Number);
  const d = new Date(year, month - 1, day);
  if (t.startzeit) {
    const [h, m] = t.startzeit.split(":").map(Number);
    d.setHours(h, m, 0, 0);
  } else {
    d.setHours(23, 59, 0, 0);
  }
  return d > new Date();
};

const isTerminAktuell = (t) => {
  const terminDatum = new Date(t.datum);
  const jetzt = new Date();
  if (t.endzeit) {
    const [h, m] = t.endzeit.split(":").map(Number);
    terminDatum.setHours(h, m);
  } else if (t.startzeit) {
    const [h, m] = t.startzeit.split(":").map(Number);
    terminDatum.setHours(h, m);
  }
  return terminDatum > jetzt;
};

// ── Main App ───────────────────────────────────────────────────────────────
export {
  supabase,
  T,
  KATEGORIEN,
  SKILLS,
  SKILLS_LABELS,
  getSkillLabel,
  MEDAILLEN,
  MEDAILLEN_NAMEN,
  getMedailleName,
  IMPRESSUM_TEXT,
  DATENSCHUTZ_TEXT,
  AGB_TEXT,
  getMedaille,
  getNextMedaille,
  formatDate,
  getKat,
  getGemeindeByPlz,
  isKlarname,
  isTerminNochNichtGestartet,
  isTerminAktuell,
};
